apiVersion: v1
kind: PersistentVolume
metadata:
  name: url-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/urls.json
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: url-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
